# Generated by Django 3.2.6 on 2025-05-15 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('subfamily', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
                'db_table': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('id_admin', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_admin', models.IntegerField(blank=True, null=True, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='home.family')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='SubFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('id_admin', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'SubFamily',
                'verbose_name_plural': 'SubFamilies',
                'db_table': 'subfamily',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_year', models.IntegerField()),
                ('last_update', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='home.catalog')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogs', to='home.product')),
            ],
            options={
                'verbose_name': 'Product Catalog',
                'verbose_name_plural': 'Product Catalogs',
                'db_table': 'product_catalog',
            },
        ),
        migrations.CreateModel(
            name='ProductABC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True)),
                ('units_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('inventory_close_u', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True)),
                ('inventory_close_p', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True)),
                ('monthly_roi', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('sold_average_month', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('profit_average_month', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('actual_inventory', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('average_selling_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_average_u', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_average_p', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_days', models.IntegerField(blank=True, null=True)),
                ('sales_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('acc_sales_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('sold_abc', models.CharField(blank=True, max_length=1, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('acc_profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('profit_abc', models.CharField(blank=True, max_length=1, null=True)),
                ('top_products', models.CharField(blank=True, max_length=2, null=True)),
                ('month_sale_u_january', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_january', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_january', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_january', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_february', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_february', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_february', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_february', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_march', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_march', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_march', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_march', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_april', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_april', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_april', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_april', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_may', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_may', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_may', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_may', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_june', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_june', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_june', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_june', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_july', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_july', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_july', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_july', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_august', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_august', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_august', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_august', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_september', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_september', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_september', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_september', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_october', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_october', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_october', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_october', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_november', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_november', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_november', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_november', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_u_december', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('month_sale_p_december', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_u_december', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('inventory_close_p_december', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('assigned_company', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('last_update', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abc_products', to='home.catalog')),
            ],
            options={
                'verbose_name': 'Product ABC',
                'verbose_name_plural': 'Products ABC',
                'db_table': 'product_abc',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subfamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='home.subfamily'),
        ),
    ]
