# Generated by Django 3.2.6 on 2025-05-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='subfamily',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
