# Generated by Django 3.2.6 on 2025-05-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.CharField(max_length=191),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['description'], name='description'),
        ),
    ]
