# Generated by Django 3.2.6 on 2025-05-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250511_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
