# Generated by Django 3.2.6 on 2025-06-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250521_1942'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productabc',
            constraint=models.UniqueConstraint(fields=('catalog_id', 'year', 'assigned_company'), name='catalog_year_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcatalog',
            constraint=models.UniqueConstraint(fields=('product_id', 'add_year'), name='product_year_idx'),
        ),
    ]
