# Generated by Django 3.2.6 on 2025-06-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_unique_id_admin'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catalog',
            constraint=models.UniqueConstraint(fields=('name',), name='catalog_name_unix_idx'),
        ),
    ]
