# Generated by Django 3.2.6 on 2025-06-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_unique_catalog_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brand',
            name='id_admin_brand_unique_idx',
        ),
        migrations.RemoveConstraint(
            model_name='catalog',
            name='catalog_name_unix_idx',
        ),
        migrations.RemoveConstraint(
            model_name='family',
            name='id_admin_family_unique_idx',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='id_admin_product_unique_idx',
        ),
        migrations.RemoveConstraint(
            model_name='subfamily',
            name='id_admin_subfamily_unique_idx',
        ),
        migrations.AddField(
            model_name='brand',
            name='enterprise',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='family',
            name='enterprise',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='enterprise',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='subfamily',
            name='enterprise',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('id_admin', 'enterprise'), name='enterprise_id_admin_brand_unique_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalog',
            constraint=models.UniqueConstraint(fields=('name',), name='catalog_name_unique_idx'),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(fields=('id_admin', 'enterprise'), name='enterprise_id_admin_family_unique_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('id_admin', 'enterprise'), name='enterprise_id_admin_product_unique_idx'),
        ),
        migrations.AddConstraint(
            model_name='subfamily',
            constraint=models.UniqueConstraint(fields=('id_admin', 'enterprise'), name='enterprise_id_admin_subfamily_unique_idx'),
        ),
    ]
