# Generated by Django 3.2.6 on 2025-06-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_unique_enterprise__id_admin'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movements',
            constraint=models.UniqueConstraint(fields=('id_admin', 'enterprise'), name='enterprise_id_admin_unique'),
        ),
    ]
