# Generated by Django 3.2.6 on 2025-06-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_movements_unique_enterprise__id_admin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movements',
            name='enterprise_id_admin_unique',
        ),
        migrations.AddConstraint(
            model_name='movements',
            constraint=models.UniqueConstraint(fields=('id_admin', 'enterprise'), name='enterprise_id_admin_movements_unique_idx'),
        ),
        migrations.AddConstraint(
            model_name='movementsdetail',
            constraint=models.UniqueConstraint(fields=('id_admin', 'enterprise'), name='enterprise_id_admin_movement_details_unique_idx'),
        ),
    ]
