# Generated by Django 3.2.6 on 2025-06-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_productabc_actual_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='folio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='payment_method',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='movementsdetail',
            name='um',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='analysisabc',
            constraint=models.UniqueConstraint(fields=('catalog', 'enterprise', 'year'), name='analysis_abc_unique_idx'),
        ),
        migrations.AddConstraint(
            model_name='productabc',
            constraint=models.UniqueConstraint(fields=('product', 'enterprise', 'year'), name='product_abc_unique_idx'),
        ),
    ]
