# Generated by Django 3.2.6 on 2025-06-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20250610_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('enterprise', models.CharField(max_length=100)),
                ('affected_rows', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Table Update',
                'verbose_name_plural': 'Tables Updates',
                'db_table': 'table_update',
            },
        ),
    ]
