# Generated by Django 3.2.6 on 2025-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_tables_updates'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tableupdate',
            index=models.Index(fields=['enterprise', 'table_name'], name='enterprise__table_name_idx'),
        ),
    ]
