# Generated by Django 3.2.6 on 2025-06-11 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_indexes_on_table_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('report_name', models.CharField(max_length=100)),
                ('enterprise', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_configuration', to='home.brand')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_configuration', to='home.catalog')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_configuration', to='home.family')),
                ('subfamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_configuration', to='home.subfamily')),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Reports Configurations',
                'db_table': 'report_configuration',
            },
        ),
        migrations.AddIndex(
            model_name='reportconfiguration',
            index=models.Index(fields=['enterprise'], name='enterprise__idx'),
        ),
        migrations.AddConstraint(
            model_name='reportconfiguration',
            constraint=models.UniqueConstraint(fields=('enterprise', 'report_name'), name='enterprise__report_name__unique_idx'),
        ),
    ]
