# Generated by Django 3.2.6 on 2025-06-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_unique_code_products'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='code__idx'),
        ),
    ]
