# Generated by Django 3.2.6 on 2025-06-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_products_code_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementsdetail',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='home.movements'),
        ),
    ]
